### ISSUE TITLE
Disabling features causes redirect to /equipment

### ISSUE THREAD

**Issue by Boosik** [hassio-addons/addon-grocy#37] opened 2019-07-13 17:13 UTC
# Problem/Motivation

> Disabling batteries or equipment features causes redirect to /equipment

## Expected behavior

> I expect that /stockoverview will be loaded

## Actual behavior

> When batteries and/or equipment features are disabled, Grocy will redirect to /equipment page. This is especially bad when you disable equipment feature, because it will make Grocy completely unacessible (unless you explicitly write /stockoverview to URL) 

## Steps to reproduce

> 

1. Disable any of the mentioned features in hassio addon configuration
1. Restart Grocy addon
1. Attempt to access Grocy page

## Proposed changes

> Do not redirect to disabled pages.

**Comment by sinclairpaul** [comment] 2019-07-13 17:48
Duplicate of #24 , upstream issue that will be fixed in a future release of the app.

**Closed by sinclairpaul** 2019-07-13 17:48 UTC
