### ISSUE TITLE
Won't start after update hassos

### ISSUE THREAD

**Issue by Sanderbloem050** [hassio-addons/addon-grocy#65] opened 2020-02-06 22:44 UTC
# Problem/Motivation

> Grocy doesn't start up anymore after the latest update from hassos.

## Expected behavior

>Just to startup and use it

## Actual behavior

> None

## Steps to reproduce

> 20-02-06 22:41:44 ERROR (MainThread) [hassio.addons.addon] Add-on a0d7b954_grocy have wrong options: Missing option stock_product_freezing in tweaks. Got {'culture': 'nl', 'currency': 'EUR', 'entry_page': 'stock', 'features': {'batteries': True, 'calendar': True, 'chores': True, 'equipment': True, 'recipes': True, 'shoppinglist': True, 'stock': True, 'tasks': True}, 'tweaks': {'chores_assignment': True, 'multiple_shopping_lists': True, 'stock_best_before_date_tracking': True, 'stock_location_tracking': True, 'stock_price_tracking': True, 'stock_product_opened_tracking': True}, 'ssl': True, 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem'}

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment] 2020-02-06 22:48
Please post the addon and supervisor logs, also check the issue at #62

**Comment by sinclairpaul** [comment] 2020-02-06 22:50
Under tweaks add `"stock_product_freezing": true`

Duplicate of #62 I am guessing the supervisor doesn't update arrays in the config.

**Comment by Sanderbloem050** [comment] 2020-02-06 22:52
Thank you that solved the issue.

**Closed** 2020-02-06 22:51 UTC
