### ISSUE TITLE
404 error page not found when adding item

### ISSUE THREAD

**Issue by Tekno-man** [hassio-addons/addon-grocy#55] opened 2019-10-18 09:17 UTC
# Problem/Motivation
When I try to create an item in the grocery list in comes up with 404 page not found.
> (Why the issue was filed)

## Expected behavior
Not sure page should follow after clicking add item but a page should load
> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce
I added the Hassio addon logged in under admin, went to add item and was presented with 404 after each item was added. Happens internally or externally. I have nginx add on running.
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment] 2019-10-18 12:39
You would need to post the addon logs, but I am guessing this is a duplicate of #36

**Comment by Tekno-man** [comment] 2019-10-19 03:08
Here is the add on logs

"[19/Oct/2019:14:05:32 +1100] 302 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET / HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
2019/10/19 14:05:33 [error] 737#737: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: equipmentItem in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 67PHP message: PHP Notice:  Trying to get property 'id' of non-object in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 67PHP message: PHP Notice:  Undefined variable: equipmentItem in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 67PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 67PHP message: PHP Notice:  Undefined variable: equipmentItem in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 87PHP message: PHP Notice:  Trying to get property 'id' of non-object in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 87PHP message: PHP Notice:  Undefined variable: equipmentItem in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 87PHP message: PHP Notice:  Trying to get property 'name' of non-object in /data/grocy/viewcache/ae4d59caf4d65b92d467994407e8b3d197f80768.php on line 87" while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-grocy.local.hass.io, request: "GET /equipment HTTP/1.1", upstream: "fastcgi://127.0.0.1:9002", host: "valletta.duckdns.org", referrer: "https://valletta.duckdns.org/a0d7b954_grocy"
[19/Oct/2019:14:05:33 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /equipment HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:34 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /viewjs/equipment.js?v=2.4.4 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:36 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:36 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /api/objects/equipment/undefined HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:36 +1100] 204 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:43 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /shoppinglist HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:45 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:45 +1100] 204 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:49 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /shoppinglistitem/new?list=1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:50 +1100] 204 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:05:50 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:06:04 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /product/new?prefillname=Flour&returnto=/https://valletta.duckdns.orgshoppinglistitem/new?list%3D1 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:06:05 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /api/system/db-changed-time HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:06:05 +1100] 204 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) PUT /api/user/settings/auto_night_mode_enabled HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:06:38 +1100] 200 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) POST /api/objects/products HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)
[19/Oct/2019:14:06:39 +1100] 404 192.168.1.1, 172.30.33.11, 172.30.32.1(172.30.32.2) GET /https://valletta.duckdns.orgshoppinglistitem/new?list?createdproduct=Flour HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36)"

**Comment by sinclairpaul** [comment] 2019-10-19 12:42
It is a duplicate of #36 
The returnto variable will fail `GET /product/new?prefillname=Flour&returnto=/https://valletta.duckdns.orgshoppinglistitem/new?list%3D1`

You can either just click back (as its really just a cosmetic error, the data will be added), or expose the addon and access using that port (i.e. not under ingress).

**Closed by sinclairpaul** 2019-10-19 12:42 UTC
Labels: potential-duplicate
